### ISSUE TITLE
Gamepad mapping issue

### ISSUE THREAD

**Issue by superrune** [mmatyas/pegasus-frontend#604] opened 2020-03-17 07:50 UTC
Hi,

I am testing Pegasus on RetroPie 4 on a Raspberry Pi 3. I have a pair of iNNEXT USB SNES-style gamepads, which are quite popular and have good reviews on Amazon. They work without issues in EmulationStation and RetroPie in general, but the mapping is completely off in Pegasus. The directional buttons are mapped to the analog stick, and not a single one of the other buttons (L-buttons, ABXY, start and select) are mapped correctly. I think this gamepad use a pretty standard USB-/HID-controller layout, and I was wandering if this is a known issue?

I can't find the documentation for mapping the gamepad. Could someone point me in the right direction?

**Comment by mmatyas** [comment] 2020-03-17 08:53
Hi, yes, Pegasus tries to guess the gamepad layout, but sometimes this ends up being incorrect due to differences in the Pi input drivers. You can change the layout in Pegasus under *Settings > Change gamepad layout*. Temporarily connecting a keyboard can also make this a bit easier.

**Comment by superrune** [comment] 2020-03-17 14:14
Hi, I've tried changing the layout, but have no idea how it works. Might be I'm going about it the wrong way. Whatever I do, the layout doesnt seem to change. Is there a tutorial or some documentation somewhere?

**Comment by Danoposada** [comment] 2020-09-17 00:15
I'm having similar issues. I'm running alpha 14 dirty (2020-09-14) and If I connect the game pad, the selection will automatically jump to the first game on the list. I already tried chaging the inputs through "Settings > Change gamepad layout"but haven't been able to (I'm not understanding how to do it) and starting Pegasus with _--disable-gamepad-autoconfig_ doesn't change a thing.

Am I missing something?

It would be nice

**Comment by Elratauru** [comment] 2020-09-24 05:52
I'm having the same problem, I have two CY-822B arcade encoders and while they work perfectly with EmulationStation and Retroarch it seems that Pegasus is mapping them to whatever it wants (not only that, none of my buttons are accept or menu so I tried to connect a Dualshock 4 to even reach the menu at all).

I also tried running it with the flag specified in the release doc (--disable-gamepad-autoconfig) and it doesnt do anything to me either way.

Is there any documentation if is it possible to set it on settings.txt and have it read from there?

**Comment by mmatyas** [comment] 2020-09-24 16:02
Yes, there seem to be button layout issues with various gamepads at the moment -- unfortunately, as there are actual hardware devices involved, I'm having troubles with testing and reproducing the bugs, but as soon as there are some developments, I'll update this issue.

Now, in Pegasus' settings directory (`~/.config/pegasus-frontend/` or `C:\Users\[username]\AppData\Local\pegasus-frontend\`), there's a `lastrun.log` file, and, if the default gamepad layout was changed, an `sdl_controllers.txt` file too. These should contain some info about the connected gamepads, so if you could attach these files, that'd help.

In addition, there's this tool: https://generalarcade.com/gamepadtool/ which handles gamepads similarly. After configuring a gamepad, you should get a long text like `GamepadName,a:b0,b:b1,x:...`, as on the bottom of the screenshot. If you could copy such "mappings" of correct configurations here, that'd also help.

**Comment by mmatyas** [comment] 2021-02-04 20:58
I've just updated the list of recognized gamepads, could you check the latest version whether it improves controller support for for you?

**Comment by mmatyas** [comment] 2021-08-29 17:24
Closing for now, feel free to report if the issue is still there!

**Closed by mmatyas** 2021-08-29 17:24 UTC
Labels: gamepad, needs testing
