### ISSUE TITLE
Steam games not found if Steam installed with Flatpak

### ISSUE THREAD

**Issue by merwok** [mmatyas/pegasus-frontend#657] opened 2020-06-10 20:56 UTC
Pegasus and Steam are installed using Flatpak (in user mode, not system).
0 Steam games are detected when Pegasus starts (from console logs).

(If there is a graphical way of configuring the Steam dir, I can’t access it due to https://github.com/flathub/org.pegasus_frontend.Pegasus/issues/1)

**Comment by mmatyas** [comment] 2020-06-11 17:50
Hm I can add support for this in the non-Flatpak version, but I'm not sure if I have the permission to access Flatpak-Steam's files and launch it from inside another Flatpak. Will try it out.

**Comment by merwok** [comment] 2020-06-14 22:26
I have now tried out a few themes and set up skyscraper to download metadata (and a custom config to run PICO-8 games :slightly_smiling_face:)
The problem is not just Steam: emulators under `/usr/bin` (installed with system package manager) are not accessible inside the flatpak container!  So that’s a big issue.

I have installed the Flatseal program to look around, but a fix in Pegasus flatpak config would be the best thing.

**Comment by mmatyas** [comment] 2020-06-15 14:28
I'm experimenting with accessing Flatpak-Steam's files from Flatpak-Pegasus but had no luck so far. It seems I can only access another app's `/run` directory, but in our case that doesn't help.

About other emulators, technically they could be installed anywhere on the system (eg. `/opt` or `/usr/local/`), so I wonder what would be the correct approach here. Giving read rights by default to root directories might be questionable from the point of sandboxing (but could be documented separately).

**Comment by HugLifeTiZ** [comment] 2020-06-17 16:41
I would imagine that liberal use of [flatpak-spawn --host](https://www.mankier.com/1/flatpak-spawn) needs to be employed here. I guess the question would be, do we expect Pegasus to automatically flatpak-spawn --host on any command in metadata.txt, do we expect the user to configure that themselves, or do we want to add a command line option?

**Comment by HugLifeTiZ** [comment] 2020-06-17 16:44
What if you give a manual filesystem override to `~/.var/app/com.valvesoftware.Steam`? Flatpak steam keeps its files in there.

**Comment by merwok** [comment] 2020-07-03 21:08
So this is really two problems:
- pegasus doesn’t detect flatpak steam
- flatpak pegasus doesn’t have access to system emulators

**Comment by mmatyas** [comment] 2020-07-06 19:05
@merwok Yes, that seems to be the case. For the former, manually adding Flatpak's internal Steam dir might help (assuming it's the same on all platforms). For the latter, adding global access to the whole root might be necessary. There's also [flatpak-spawn](https://www.mankier.com/1/flatpak-spawn) from https://github.com/flathub/org.pegasus_frontend.Pegasus/issues/3, which might actually solve that, but haven't had the time to test it yet.

**Comment by mmatyas** [comment] 2020-08-25 20:04
After some experimenting, I can confirm that the flatpak-spawn solution works and with some permission changes I can now launch both native and flatpak Steam from both native and flatpak Pegasus, as well as any other native emulators. I've just added support for flatpak-Steam in the latest native build of Pegasus, and I can update the flatpak version too in the next stable release (I'm waiting for the update on the KDE stack).

**Comment by mmatyas** [comment] 2020-09-17 15:44
With the new stable release this should be now fixed!

**Closed by mmatyas** 2020-09-17 15:44 UTC
Labels: ext-steam, feature, os-linux

**Comment by merwok** [comment] 2020-09-17 15:57
It works!  Fantastic!
