### ISSUE TITLE
(AUR - Manjaro) Pegasus will not start. [w] qrc:/frontend/main.qml:191:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated.

### ISSUE THREAD

**Issue by Kintah** [mmatyas/pegasus-frontend#661] opened 2020-06-26 20:24 UTC
```
[i] Pegasus alpha13-114-gfa688c8 (2020-06-15)
[i] Running on Manjaro Linux (x86_64, xcb)
[i] Program settings loaded (`/home/kintah/.config/pegasus-frontend/settings.txt`)
[i] Found locale `de`
[i] Found locale `en`
[i] Found locale `en`
[i] Found locale `es`
[i] Found locale `fr`
[i] Found locale `hu`
[i] Found locale `ko`
[i] Found locale `pt-BR`
[i] Found locale `ru`
[i] Found locale `zh`
[i] Locale set to `en`
[i] Found theme `Pegasus Grid` at `:/themes/pegasus-theme-grid/`
[i] Theme set to `Pegasus Grid` (`:/themes/pegasus-theme-grid/`)
[i] SDL version 2.0.12
[w] qrc:/frontend/main.qml:191:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[i] Metafiles: finished game searching in 0ms
[i] Steam: found data directory: `/home/kintah/.local/share/Steam/`
[i] Steam: finished game searching in 1ms
[w] EmulationStation: system config file not found
[i] EmulationStation: finished game searching in 0ms
[i] Lutris: found data directory: `/home/kintah/.local/share/lutris/`
Segmentation fault (core dumped)

```
I installed it from the AUR. Pegasus will not open.
Also the only thing in the config folder is lastrun.log. no settings.txt and no theme folder

**Comment by LordSchwenk** [comment] 2020-06-27 20:22
Same here in Zorin OS 15.2 (Ubuntu 18.04 based). Exit after Lutris load with Segmentation fault.

**Comment by mmatyas** [comment] 2020-06-27 21:38
Hi, it seems Manjaro updated the Qt libs to 5.15, which is apparently not fully backward compatible.  At the moment Pegasus is based on Qt 5.12, but I'll see if it can be upgraded. As a workaround you should be still able to use the generic Linux builds from https://pegasus-frontend.org.

**Comment by LordSchwenk** [comment] 2020-06-28 14:43
I have installed this Linux build from the website you mentioned: Latest version (Debian package): 0.13.114.
It gaves me this Error i had posted.

**Comment by sanecito** [comment] 2020-07-21 00:08
I can confirm it seems related to Qt libs as well (also using [pegasus-frontend-git on AUR](https://aur.archlinux.org/packages/pegasus-frontend-git/)). For reference, running:
```
Operating System: Arch Linux
KDE Plasma Version: 5.19.3
KDE Frameworks Version: 5.72.0
Qt Version: 5.15.0
Kernel Version: 5.7.9-arch1-1
OS Type: 64-bit
```
As a mindless workaround for any distro I recommend installing it via Flatpak (available via [Flathub](https://flathub.org/apps/details/org.pegasus_frontend.Pegasus)) which given how Flatpak works tends to avoid these kinds of issues. Have had no issues w/ Flatpak version thus far.

**Comment by mmatyas** [comment] 2020-08-12 16:19
@Kintah I've just fixed a Lutris-related crash, could you try whether the latest release resolves the issue for you?

**Comment by eskay993** [comment] 2020-08-30 19:48
Hi

I'm having the same issue with the AUR version. I've tested the generic versions currently on the site as you suggest.

pegasus-fe_alpha13_x11-static - **Works**
pegasus-fe_alpha13-149-g0067817_x11-static - **Same error as AUR version**

My system:
```
Distro: Manjaro Linux 
Kernel: 5.7.17-2-MANJARO x86_64 bits: 64
Desktop: KDE Plasma 5.19.4 
Qt Version: 5.15.0
```
Cheers

**Comment by mmatyas** [comment] 2020-09-01 13:21
Could you post the full log? I've also received reports of Pegasus working on Manjaro, so this might be related to one of the compatibility modules.

**Comment by eskay993** [comment] 2020-09-01 19:35
Not sure if this is the full log, so let me know if there is a way to get more detail.

I've inlcuded the Flatpak ones as well for good measure, which works fine.

Couple of things I just noticed...

Even with the working generic one one, I get a segmentation fault but this only happens after I successfully launch into Pegasus, then quit from the main menu.

Also, looks like the working looks like the non-working is picking up (or trying to) my Lutris games. The other 2 are not.

**pegasus-fe_alpha13_x11-static (Working)**

> [i] Program settings loaded
[i] Pegasus alpha13 (2019-10-09)
[i] Running on Manjaro Linux (x86_64, xcb)
[i] Found locale `de`
[i] Found locale `en`
[i] Found locale `es`
[i] Found locale `fr`
[i] Found locale `hu`
[i] Found locale `ko`
[i] Found locale `pt-BR`
[i] Found locale `ru`
[i] Locale set to `en`
[i] Found theme 'Pegasus Grid' (`:/themes/pegasus-theme-grid/`)
[i] Found theme 'gameOS' (`/home/fakeuser/.config/pegasus-frontend/themes/gameOS/`)
[i] Theme set to 'Pegasus Grid' (`:/themes/pegasus-theme-grid/`)
[i] SDL version 2.0.12
[i] Metafiles: finished game searching in 0ms
[i] Steam: found data directory: `/home/fakeuser/.local/share/Steam/`
[i] Steam: finished game searching in 0ms
[w] EmulationStation: system config file not found
[i] EmulationStation: finished game searching in 0ms
[i] Game list post-processing took 0ms
[i] Metafiles: finished asset searching in 0ms
[i] Games found in 0ms
[w] qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
[w] qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
[w] Steam: failed to parse the response of the server for game `Proton 5.0` - perhaps the Steam API changed?
[i] Steam: finished asset searching in 332ms
[i] EmulationStation: finished asset searching in 0ms
[i] Skraper Assets: 0 assets found
[i] Skraper Assets: finished asset searching in 0ms
[i] Assets and metadata found in 333ms
[i] 2 games found
[i] Closing Pegasus, goodbye!
Segmentation fault (core dumped)


**pegasus-fe_alpha13-149-g0067817_x11-static (Not working)**

> [i] Pegasus alpha13-149-g0067817 (2020-08-25)
[i] Running on Manjaro Linux (x86_64, xcb)
[i] Qt version 5.15.0
[i] Program settings loaded (`/home/fakeuser/.config/pegasus-frontend/settings.txt`)
[i] Found locale `de`
[i] Found locale `en`
[i] Found locale `en`
[i] Found locale `es`
[i] Found locale `fr`
[i] Found locale `hu`
[i] Found locale `ko`
[i] Found locale `pt-BR`
[i] Found locale `ru`
[i] Found locale `zh`
[i] Locale set to `en`
[i] Found theme `Pegasus Grid` at `:/themes/pegasus-theme-grid/`
[i] Found theme `gameOS` at `/home/fakeuser/.config/pegasus-frontend/themes/gameOS/`
[i] Theme set to `Pegasus Grid` (`:/themes/pegasus-theme-grid/`)
[i] SDL version 2.0.12
[w] qrc:/frontend/main.qml:191:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
[i] Metafiles: finished game searching in 0ms
[i] Steam: found data directory: `/home/fakeuser/.local/share/Steam/`
[i] Steam: finished game searching in 0ms
[w] EmulationStation: system config file not found
[i] EmulationStation: finished game searching in 0ms
[i] Lutris: found data directory: `/home/fakeuser/.local/share/lutris/`
[i] Lutris: finished game searching in 0ms
Segmentation fault (core dumped)

**Flatpak version**

> [i] Program settings loaded
[i] Pegasus 93b42ae (2019-10-09)
[i] Running on KDE Flatpak runtime (x86_64, xcb)
[i] Found locale `de`
[i] Found locale `en`
[i] Found locale `es`
[i] Found locale `fr`
[i] Found locale `hu`
[i] Found locale `ko`
[i] Found locale `pt-BR`
[i] Found locale `ru`
[i] Locale set to `en`
[i] Found theme 'Pegasus Grid' (`:/themes/pegasus-theme-grid/`)
[i] Found theme 'gameOS' (`/home/fakeuser/.var/app/org.pegasus_frontend.Pegasus/config/pegasus-frontend/themes/gameOS/`)
[i] Theme set to 'Pegasus Grid' (`:/themes/pegasus-theme-grid/`)
[i] SDL version 2.0.9
[i] Metafiles: finished game searching in 0ms
[i] Steam: found data directory: `/home/fakeuser/.steam/steam/`
[i] Steam: finished game searching in 0ms
[i] GOG: 0 games found
[i] GOG: finished game searching in 0ms
2020-09-01T20:29:26 [w] EmulationStation: system config file not found
[i] EmulationStation: finished game searching in 0ms
[i] Game list post-processing took 0ms
[i] Metafiles: finished asset searching in 0ms
2020-09-01T20:29:26 [w] Icon theme "la-capitaine-custom-icon-theme" not found.
[i] Games found in 1ms
2020-09-01T20:29:27 [w] Steam: failed to parse the response of the server for game `Proton 5.0` - perhaps the Steam API changed?
[i] Steam: finished asset searching in 342ms
[i] GOG: finished asset searching in 0ms
[i] EmulationStation: finished asset searching in 0ms
[i] Skraper Assets: 0 assets found
[i] Skraper Assets: finished asset searching in 0ms
[i] Assets and metadata found in 342ms
[i] 2 games found
[i] Closing Pegasus, goodbye!

**Comment by mmatyas** [comment] 2020-09-07 18:53
Sorry for the late reply, could you try the following? Create a `settings.txt` under `~/.config/pegasus-frontend/` (or open if exists) and set its contents to: 

```
providers.steam.enabled: false
providers.gog.enabled: false
providers.es2.enabled: false
providers.skraper.enabled: false
providers.lutris.enabled: false
```

then start Pegasus. If it works then the bug is in one of these compatibility modules: you could then find which it is by turning them `true` one by one. I have a feeling it's Lutris, as that was added after alpha 13, but might be something else.

**Comment by eskay993** [comment] 2020-09-08 18:36
Thanks for looking into this. Unfortuantely I am travelling at the moment for a few weeks and don't have access to my machine. I will check the above when I return (or when I build build another mahicne, which may be sooner :))

**Comment by barolo** [comment] 2020-09-09 06:40
I'm running a self compiled Pegasus with 5.15 without any problems, I see various stuff spamming Xorg.log with the "Implicitly defined onFoo properties in Connections" errors but nothing is breaking

**Comment by mmatyas** [comment] 2021-01-23 10:10
Both the Lutris crash and the warning spam should be now fixed so I think this can be safely closed. Feel free to report if something still doesn't work!

**Closed by mmatyas** 2021-01-23 10:10 UTC
Labels: bug, needs testing, os-linux

**Comment by ezerez** [comment] 2021-01-24 16:40
I Still get this error when I run the latest version on PopOS. The flatpak version runs though.

[i] Pegasus alpha14-106-g6522a09b (2021-01-21)
[i] Running on Pop!_OS 20.10 (x86_64, xcb)
[i] Qt version 5.15.2
[i] Program settings loaded (`/home/jelle/.config/pegasus-frontend/settings.txt`)
[i] Found locale `bs`
[i] Found locale `de`
[i] Found locale `en-GB`
[i] Found locale `en`
[i] Found locale `es`
[i] Found locale `fr`
[i] Found locale `hu`
[i] Found locale `ko`
[i] Found locale `nl`
[i] Found locale `pt-BR`
[i] Found locale `ru`
[i] Found locale `zh-TW`
[i] Found locale `zh`
[i] Locale set to `en`
[i] Found theme `Pegasus Grid` at `:/themes/pegasus-theme-grid/`
[i] Theme set to `Pegasus Grid` (`:/themes/pegasus-theme-grid/`)
[i] SDL version 2.0.12
[i] Metafiles: No metadata files found
[i] Metafiles: Finished searching in 0ms
[i] Media: Finished searching in 0ms
[i] Favorites: Finished searching in 0ms
[i] Playtime: Finished searching in 0ms
[i] Steam: Found installation at `/home/hidden/.steam/steam/`
[i] Steam: 2 games found
[i] Steam: Finished searching in 1ms
[i] Logiqx: Finished searching in 0ms
[i] Lutris: Found data directory: `/home/hidden/.local/share/lutris/`
[i] Lutris: Finished searching in 0ms
[i] Game list post-processing took 0ms
[i] 3 games found
Segmentation fault (core dumped)
