### ISSUE TITLE
After the first launch on Windows 10, a static image is displayed that does not respond to anything

### ISSUE THREAD

**Issue by Korb** [mmatyas/pegasus-frontend#1131] opened 2024-09-25 09:43 UTC
### The issue

Subj.

The top of the screen displays the GOG and Steam logos and names, with text displayed on the left side:

> src=" https://items.gog.com/not_a_cp/RU_product-page-addons.png ">
> *Единоразовая скидка действует только для предзаказов Cyberpunk 2077, оформленных в магазине GOG.COM до 18 июня 2019 года, 1:00 по московскому времени. Скидка распространяется на все доступные товары в…

### System info

Microsoft Windows 10.0.19045.4894

### Pegasus version

Pegasus Weekly release 20, 2023 (Aug 16, 2023)

### Pegasus log

```
2024-09-25T12:28:52 [i] Pegasus alpha16-51-g6421d7a7 (2023-05-21)
2024-09-25T12:28:52 [i] Running on Windows 10 Version 2009 (x86_64, windows)
2024-09-25T12:28:52 [i] Qt version 5.15.6
2024-09-25T12:28:52 [i] Program settings loaded (`C:/Users/Korb/AppData/Local/pegasus-frontend/settings.txt`)
2024-09-25T12:28:52 [i] Found locale `ar`
2024-09-25T12:28:52 [i] Found locale `bs`
2024-09-25T12:28:52 [i] Found locale `ca`
2024-09-25T12:28:52 [i] Found locale `de`
2024-09-25T12:28:52 [i] Found locale `en-GB`
2024-09-25T12:28:52 [i] Found locale `en`
2024-09-25T12:28:52 [i] Found locale `es`
2024-09-25T12:28:52 [i] Found locale `fr`
2024-09-25T12:28:52 [i] Found locale `hu`
2024-09-25T12:28:52 [i] Found locale `ja`
2024-09-25T12:28:52 [i] Found locale `ko`
2024-09-25T12:28:52 [i] Found locale `lt`
2024-09-25T12:28:52 [i] Found locale `nl`
2024-09-25T12:28:52 [i] Found locale `pt-BR`
2024-09-25T12:28:52 [i] Found locale `ru`
2024-09-25T12:28:52 [i] Found locale `zh-TW`
2024-09-25T12:28:52 [i] Found locale `zh`
2024-09-25T12:28:52 [i] Locale set to `ru`
2024-09-25T12:28:52 [i] Found theme `Pegasus Grid` at `:/themes/pegasus-theme-grid/`
2024-09-25T12:28:52 [i] SDL version 2.0.20
2024-09-25T12:28:52 [i] Theme set to `Pegasus Grid` (`:/themes/pegasus-theme-grid/`)
2024-09-25T12:28:54 [i] Metafiles: No metadata files found
2024-09-25T12:28:54 [i] Metafiles: Finished searching in 0ms
2024-09-25T12:28:54 [i] Media: Finished searching in 0ms
2024-09-25T12:28:54 [i] Steam: Found installation at `c:/steam/`
2024-09-25T12:28:54 [i] Steam: Found `c:/steam/config/config.vdf`
2024-09-25T12:28:54 [i] Steam: Found `c:/steam/steamapps/libraryfolders.vdf`
2024-09-25T12:28:54 [i] Steam: 2 games found
2024-09-25T12:28:54 [i] Steam: Finished searching in 162ms
2024-09-25T12:28:54 [i] GOG: 1 games found
2024-09-25T12:28:54 [i] GOG: Finished searching in 5ms
2024-09-25T12:28:54 [i] EmulationStation: No installation found
2024-09-25T12:28:54 [i] EmulationStation: Finished searching in 1ms
2024-09-25T12:28:54 [i] LaunchBox: No installation found
2024-09-25T12:28:54 [i] LaunchBox: Finished searching in 0ms
2024-09-25T12:28:54 [i] Logiqx: Finished searching in 0ms
2024-09-25T12:28:54 [i] Playnite: No installation found
2024-09-25T12:28:54 [i] Playnite: Finished searching in 0ms
2024-09-25T12:28:54 [i] Skraper Assets: 0 assets found
2024-09-25T12:28:54 [i] Skraper Assets: Finished searching in 0ms
2024-09-25T12:28:54 [i] Favorites: Finished searching in 0ms
2024-09-25T12:28:54 [i] Playtime: Finished searching in 0ms
2024-09-25T12:28:54 [i] Waiting for online sources...
2024-09-25T12:28:55 [i] Waiting for online sources took 729ms
2024-09-25T12:28:55 [i] Game list post-processing took 0ms
2024-09-25T12:28:55 [i] 3 games found
2024-09-25T12:28:57 [w] qrc:/themes/pegasus-theme-grid/layer_gameinfo/PanelRight.qml:128:5: QML Text: Error decoding: qrc:/themes/pegasus-theme-grid/layer_gameinfo/PanelRight.qml: Unsupported image format
2024-09-25T12:28:57 [w] qrc:/themes/pegasus-theme-grid/layer_gameinfo/PanelLeft.qml:43:9: QML Text: Error decoding: qrc:/themes/pegasus-theme-grid/layer_gameinfo/PanelLeft.qml: Unsupported image format
2024-09-25T12:28:58 [w] qrc:/themes/pegasus-theme-grid/layer_gameinfo/PanelLeft.qml:43:9: QML Text: Error decoding: qrc:/themes/pegasus-theme-grid/layer_gameinfo/PanelLeft.qml: Unsupported image format
2024-09-25T12:28:58 [w] qrc:/themes/pegasus-theme-grid/layer_gameinfo/PanelLeft.qml:43:9: QML Text: Error decoding: qrc:/themes/pegasus-theme-grid/layer_gameinfo/PanelLeft.qml: Unsupported image format
2024-09-25T12:28:58 [w] qrc:/themes/pegasus-theme-grid/layer_gameinfo/PanelLeft.qml:43:9: QML Text: Error decoding: qrc:/themes/pegasus-theme-grid/layer_gameinfo/PanelLeft.qml: Unsupported image format
```

![2024-09-25_12-30-04](https://github.com/user-attachments/assets/afef7310-8798-4fb9-b011-899cd7465b26)

**Comment by mmatyas** [comment] 2024-09-25 19:37
Hi! By "after the first launch", do you mean this is the very first time you launch Pegasus, or that it worked the first time, but when you now open it, it doesn't? Can you not open the menu either (with Esc)? Also could you try the latest version, `alpha16-82 (2024-09-16)`?

**Comment by Korb** [comment] 2024-09-26 09:23
> Hi! By "after the first launch", do you mean this is the very first time you launch Pegasus

Yes.

> Can you not open the menu either (with Esc)?

Yes. The same thing happens when I press F1 (which is good).

But it's not obvious. Based on my UX, I would try `Alt`/`F9` first (no response), then `Win-key`/`Alt+Tab` (to make sure the app isn't frozen), `Ctrl+O` (Options/Open), `Tab` (switches between interactive objects in the accessible interface), `Alt+Enter`/`F11` (switches between windowed and fullscreen modes)...

So, I think this ticket can be closed. The issue was not that the application does not respond to user actions, but that the interface is not obvious in its functionality and does not tell the user what he can do in it / how to interact with it. There are no hints, including when hovering the mouse cursor over various elements of the application window, which, according to the user's assumption, may be interactive when pressing LMB / RMB.

> Also could you try the latest version, `alpha16-82 (2024-09-16)`?

I tried `pegasus-fe_alpha16-82-gc3462e68_win-mingw-static.zip` version and its behavior, as far as I can see, is no different from the behavior of the Weekly release 20, 2023 version.

**Comment by mmatyas** [comment] 2024-09-29 20:38
So if I understand correctly, using Esc/F1 does work and opens the menu; the issue is the lack of on-screen indicators in the default theme. I'll close the issue then, let me know if I misunderstood!

**Closed by mmatyas** 2024-09-29 20:38 UTC
