### ISSUE TITLE
Add Native PS4 Controller Support

### ISSUE THREAD

**Issue by arnoldsecret** [mmatyas/pegasus-frontend#443] opened 2019-04-07 02:07 UTC
Unlike PS3 controllers that use it's own propietary cables, PS4 controllers are USB, meaning it can be hooked up to any device with USB 2.0 or 3.0.

In non-native games, it uses Directinput for its controls, meaning it needs a program like x360ce or DS4Windows/InputMapper for Xinput support.

**Comment by mmatyas** [comment] 2019-04-07 16:37
Yes, DirectInput is not too well supported at the moment, but I'd like to improve that in the future. I think this is a duplicate of #196, so closing for now (but feel free to leave comments if that issue doesn't really match).

**Closed by mmatyas** 2019-04-07 16:37 UTC

**Comment by arnoldsecret** [comment] 2019-04-11 07:35
Some PC games have native DS4 support, there's also a list of supported games at https://pcgamingwiki.com/wiki/List_of_games_that_support_DualShock_4, so it might be possible to write an API that supports it.

**Comment by mmatyas** [comment] 2019-04-11 17:04
Yes, there was an idea to replace the whole gamepad handling to something like SDL2, which would support all kinds of gamepad APIs in a crossplatform way. It's still on the roadmap, but shouldn't be too far away now.
