### ISSUE TITLE
Videopreviews looses sound after intense scrolling

### ISSUE THREAD

**Issue by AndersHP84** [mmatyas/pegasus-frontend#141] opened 2017-11-20 14:15 UTC
When browsing large collections of games (maybe because no pagedown/up is introduced), after some time the videopreviews stops playing audio.

**Comment by mmatyas** [comment] 2017-11-20 15:55
About how many games do you usually need to scroll through for this to happen? Does the audio stop playing for all videos until you restart Pegasus? Do you see any errors in the log (`~/.config/pegasus-frontend/lastrun.log`)? And the device is a Pi 3, if I remember correctly?

**Comment by mmatyas** [comment] 2018-01-11 10:44
Does the problem still persist?

**Comment by mmatyas** [comment] 2018-02-22 18:05
I'm closing this for now, but feel free comment if the problem is still there.

**Closed by mmatyas** 2018-02-22 18:05 UTC
Labels: bug
