### ISSUE TITLE
Crash after launch, related to gstreamer?

### ISSUE THREAD

**Issue by barolo** [mmatyas/pegasus-frontend#973] opened 2022-03-26 01:18 UTC
### The issue

Crash upon launch with following error:
`[i] Metafiles: Finished searching in 20ms
[i] Media: Finished searching in 0ms
[i] Logiqx: Finished searching in 0ms
[i] Skraper Assets: 0 assets found
[i] Skraper Assets: Finished searching in 0ms
[i] Favorites: Finished searching in 0ms
[i] Playtime: Finished searching in 2ms
[i] Game list post-processing took 1ms
[i] 124 games found
[i] Gamepad: Connected device 0x0 (Nintendo Switch Pro Controller)

(pegasus-fe:13090): GStreamer-GL-CRITICAL **: 02:14:13.158: gst_gl_context_new_wrapped: assertion 'available_apis != GST_GL_API_ANY' failed
[w] Could not create wrappped context for platform: 2
[1]    13090 segmentation fault  ./pegasus-fe
`

### System info

Linux Gentoo with the latest packages, the only significant change from the time I remember it working is switching to pipewire from pulseaudio.

### Pegasus version
Few of the latest weeklies, and one built from source.

**Comment by mmatyas** [comment] 2022-03-26 17:23
Hm the message comes from Qt, so I looked into the source code and the error is caused by, it seems, an API break in a GStreamer function. [Here](https://github.com/qt/qtmultimedia/blob/fd30913d4601d12437404e1d20113a1ed6364ccc/src/gsttools/qgstvideorenderersink.cpp#L371) you can see the last official Qt 5 release calls `gst_gl_context_new_wrapped` with `GST_GL_API_ANY` as its last parameter. But [GStreamer's current documentation](https://gstreamer.freedesktop.org/documentation/gl/gstglcontext.html#gst_gl_context_new_wrapped) explicitly tells to not do that. The issue is fixed in Qt 6.3, [here](https://github.com/qt/qtmultimedia/commit/20153c34a4a46a755f8a48502f0ad36d01de2e98).

So what I think you can do is either use an older GStreamer, build Qt without the gstreamer-gl feature, or backport the fix to your Qt; the significant lines are these:

```
    GstGLAPI glApi = QOpenGLContext::openGLModuleType() == QOpenGLContext::LibGL ? GST_GL_API_OPENGL : GST_GL_API_GLES2;
    GstGLContext *appContext = gst_gl_context_new_wrapped(display, (guintptr)nativeContext, glPlatform, glApi);
```

**Comment by barolo** [comment] 2022-03-26 18:28
This is problematic, Gentoo doesn't carry Qt 6 even in its testing repos. Wouldn't static builds from here mitigate this, though, at least on the Qt side?
I have downgraded gstreamer from 1.20.1 to 1.18.6, which seems to have fixed things.

**Comment by mmatyas** [comment] 2022-03-26 18:52
I'm not sure I can do something about this. The builds link to GStreamer dynamically, so if there's an API break in the latest GStreamer, then my change would break Pegasus with the older GStreamer versions. I haven't found yet whether this change was introduced in 1.20, or only the assert was added recently; if it's safe to backport the fix, I can try it.

**Comment by barolo** [comment] 2022-03-26 20:34
Aee you building against Qt6?

**Comment by mmatyas** [comment] 2022-03-27 14:06
I'm still using Qt 5, but the fix seems to be possible on that too.

**Comment by mmatyas** [comment] 2022-03-28 16:56
Ok, if this was the problem, it should be now fixed in the latest release. Give it a try!

**Comment by barolo** [comment] 2022-03-28 20:37
> Ok, if this was the problem, it should be now fixed in the latest release. Give it a try!

It works now, thanks!

**Closed** 2022-03-28 20:38 UTC
Labels: bug-qt
