### ISSUE TITLE
Pegasus doesn't even start

### ISSUE THREAD

**Issue by lilbud** [mmatyas/pegasus-frontend#30] opened 2017-06-10 20:21 UTC
I just downloaded the alpha2, and it doesn't even start. I get permission denied errors every time, even when trying to run as root.

![image](https://user-images.githubusercontent.com/9311410/27006034-c8f9b508-4df8-11e7-8350-3f238b3fa8fb.png)

**Comment by mmatyas** [comment] 2017-06-10 21:37
Hm, not having execution rights in your own home is certainly interesting. That error is also often the generic "Something's wrong" kind of system message, unfortunately: I've seen that when I tried running a program on an incorrect architecture, when I tried running a program on a different file system (eg. samba, nfs), when I had an outdated kernel, when I had an outdated system installation (eg. Debian Wheezy), or when I had no write permission to a directory or a file (maybe `~/.config` is write locked?).

Probably most of these don't apply to you, but you could do a system update just in case. Which Raspberry is this exactly? 2 or 3?

Also Pegasus should never need `sudo` rights, it should work fine as a regular user.

**Comment by mmatyas** [comment] 2017-06-10 22:02
It could also mean that the file isn't even an program, eg. when you download something with `wget`/`curl`, but it downloads the webpage instead. It could also mean the file got corrupted.

**Comment by lilbud** [comment] 2017-06-10 22:58
I am running, or trying to run this on, a Raspberry Pi 3, fully up to date. Shouldn't this be a .sh file?

**Comment by hex007** [comment] 2017-06-10 23:25
It is a binary executable. "sh" files are shell scripts like "bat" files in Windows

**Comment by mmatyas** [comment] 2017-06-11 17:23
I've just tested it on a fresh, not updated RetroPie 4.2 image, on a Pi 1 and a Pi 3, where I only installed the dependencies and `wget`ed and `unzip`ed the release, and it worked without problems. I think something has happened to your file which produces this error. So! Let's do some detective work: please post the output of

- `ls -l pegasus-fe_alpha2_rpi2-static`
   it should print `-rwxrwxr-x 1 pi pi 18219832 Jun 10 20:25 pegasus-fe_alpha2_rpi2-static`
    - if the first column is not `-rwxrwxr-x`, the file permissions were changed before or during the transfer
    - there should be 2 `pi`s after that, if not, the owner was changed, probably before the transfer
    - the size should match, the date not necessarily
- `md5sum pegasus-fe_alpha2_rpi2-static`
    - it must be `38314750faa33d74fed29c1be3bb2722`, if not, the file was damaged
    - the `md5sum` of the ZIP is `a91eafd1669ac369883a5944014753e8`
- `file pegasus-fe_alpha2_rpi2-static`
    - it should print `pegasus-fe_alpha2_rpi2-static: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32`

**Comment by lilbud** [comment] 2017-06-12 00:47
for `ls -l pegasus-fe_alpha2_rpi2-static` I get
- -rwxr-xr-x 1 pi pi 18219832 Jun 10 14:25 pegasus-fe_alpha2_rpi2-static
for `md5sum pegasus-fe_alpha2_rpi2-static` I get
- 38314750faa33d74fed29c1be3bb2722
for `file pegasus-fe_alpha2_rpi2-static` I get
- pegasus-fe_alpha2_rpi2-static: ELF 32-bit LSB executable, ARM, EABI5 version 1 (       SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2       .6.32, BuildID[sha1]=9f6c8bc35636ed947f67425198aec73326cb2051, stripped

**Comment by mmatyas** [comment] 2017-06-12 08:55
Well everything looks fine, the file is as it's supposed to be. If the OS still has problems launching it, I have to assume the problem is somewhere else on the file system...

**Comment by lilbud** [comment] 2017-06-27 13:25
Hello, I'm back. I just downloaded the new build and _surprise_ it still gives me permission denied even with sudo

**Comment by shantigilbert** [comment] 2017-06-27 18:22
Could this be a library that is linked to the executable?

**Comment by lilbud** [comment] 2017-06-29 21:21
Could the problem be that I am running Pegasus from a USB flash drive?

**Comment by mmatyas** [comment] 2017-06-30 05:55
Yes, on some file systems like NTFS, you don't have execution rights by default, despite that the file permissions look ok. But if this drive contains the whole system, it shouldn't be a problem.

**Comment by lilbud** [comment] 2017-06-30 16:02
But when I try to run Pegasus, it reports missing libraries, like Libinput, but I can't install it.

**Comment by mmatyas** [comment] 2017-06-30 16:11
So it's no longer the "permission denied" error? What's the output? What does `ldd pegasus-fe` say?

**Comment by lilbud** [comment] 2017-06-30 17:40
No more permission denied errors. I moved it to the /etc/ folder.

Here is the result of ldd pegasus-fe: https://ghostbin.com/paste/5enp3

**Comment by mmatyas** [comment] 2017-06-30 18:17
Ah, great! As for libinput, the package name is `libinput10`.

**Comment by lilbud** [comment] 2017-06-30 19:02
Thanks, it finally works. A few questions...
- How can images be scraped?
- Where are all of the program files?
- How do you access the settings menu?

**Comment by mmatyas** [comment] 2017-06-30 19:18
For how the assets are loaded, see [this post](https://retropie.org.uk/forum/topic/9598/announcing-pegasus-frontend/52).

At the moment all files, assets and translations are built into the binary. This will probably change when external theme support will get added. The settings files should be under `~/.config/pegasus-frontend/` (config files will be created/changed when you change some settings).

Currently the keys are

- Enter/A (XBox)/X (PS)/left mouse button: select option/start game
- Esc/B (XBox)/Circle (PS)/right mouse button: go back/open the main menu
- arrow keys/dpad: navigation (duh)
- A/Q/LeftShoulder/L1: previous game system
- E/D/RightShoulder/R1: next game system

Mouse scrolling and dragging is also mostly supported.

**Comment by mmatyas** [comment] 2017-07-02 20:14
Closing the issue now that the original problem got solved. Feel free to report any problems you find!

**Closed by mmatyas** 2017-07-02 20:14 UTC
Labels: help wanted

**Comment by lilbud** [comment] 2017-07-02 21:42
Maybe you should add something to the wiki? 
 Something along the lines of: DO NOT ATTEMPT TO RUN FROM A USB DRIVE
