### ISSUE TITLE
Bug - Crash when viewing a video and then selecting a different theme

### ISSUE THREAD

**Issue by iwubcode** [mmatyas/pegasus-frontend#386] opened 2019-02-26 03:55 UTC
I was using the default theme and a video was playing.  When I switched to a new theme, the program crashed.

The last log line if relevant:

```
2019-02-25T21:49:48 [w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:73:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/.svg
```

(usage settings   Windows 10, portable, tested with steam game)

**Comment by iwubcode** [comment] 2019-02-26 03:58
Hmm, it seems to occur in other scenarios too.  Example:  using 'gameOs' theme and then viewing a video, hitting the 'close' button followed by moving the cursor to a different game.

**Comment by mmatyas** [comment] 2019-02-26 17:52
I think this is just DirectPlay being generally unstable; there are some plans to use something more modern (#347) but it'll take some time. In the case of online sources like Steam the network transfer may also affect the playback. Or maybe it's just a bug caused by some other component like Qt or some other codecs.

In either case, this would need some more testing. I'm closing the issue for now due to the possible sources of the bug is too broad -- but if you find out more details or manage to always reproduce the error, feel free to update it!

**Closed by mmatyas** 2019-02-26 17:52 UTC

**Comment by Bi-noon** [comment] 2020-08-05 13:24
Hi Fluffy! This kind of issue occurs in my case with the same manner. When I select another Steam Games, the frontend crashes. I tested Pegasus with my laptop and my desktop both in Windows 10 and I still have the crash (the first time, I thought it was the release that I compiled from your project, so I tested your release, same result). When I remove the video display in my QML file, the frontend doesn't crash. 
So I suppose that it is the network transfer which may affect the playback.

Do you know how to prevent or resolve this issue ?

Thank you !
