### ISSUE TITLE
[Suggestion] Include game manuals

### ISSUE THREAD

**Issue by Joshy-2010** [mmatyas/pegasus-frontend#1020] opened 2022-09-12 22:13 UTC
Just a small idea for later: Maybe add the ability to open game manuals, like in the games tab where you can see al the different media like screenshots and fanart maybe also include a shortcut that opens a PDF programm / app or something

**Comment by mmatyas** [comment] 2022-09-13 09:43
Hi! This seems to be a duplicate of #447, I'm closing in favor of that.

**Closed by mmatyas** 2022-09-13 09:43 UTC
Labels: feature
