### ISSUE TITLE
Playnite support

### ISSUE THREAD

**Issue by polson** [mmatyas/pegasus-frontend#862] opened 2021-07-14 16:19 UTC
[Playnite ](https://playnite.link/) is an increasingly popular Windows game manager.  It comes with it's own fullscreen mode which is nice, but it's slow compared to Pegasus.

Would be nice to have support for importing Playnite metadata.  

I would be happy to work on implementing this.

**Comment by mmatyas** [comment] 2021-07-15 12:46
This sounds like the duplicate of #600, so closing for now, but feel free to work on it if you'd like!

You'd want to create a new provider under `/src/backend/providers/`, implementing the class in `Provider.h`. You can set which platforms include the directory in `providers.pri` and in the code by adding it in `/src/backend/AppSettings.cpp`. The Skraper provider is a relatively simple one you can use as an example. Good luck!

**Closed by mmatyas** 2021-07-15 12:46 UTC
Labels: feature

**Comment by polson** [comment] 2021-07-15 15:27
Ah didn't see that ticket.  Thanks!
