### ISSUE TITLE
Videos play but colors are wrong

### ISSUE THREAD

**Issue by tuxrinku** [mmatyas/pegasus-frontend#1048] opened 2023-04-06 20:09 UTC
### The issue
I scraped videos using skyscraper, everything is fine when I play them through vlc but pegasus plays them with wrong colors, like negative.

### System info

OS : Ubuntu 22.04.02
CPU: Intel N6005
GPU: Nvidia GTX 1050
RAM: 32gb

### Pegasus version
Pegasus alpha16-47-gb0366487 (2023-02-28)

### Pegasus log
[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/11174123/lastrun.log)

Maybe the last line is a hint :
`2023-04-06T22:06:13 [w] libpng warning: iCCP: profile 'Samsung - Natural Color Pro 1.0 ICM': 0h: PCS illuminant is not D50`

**Comment by mmatyas** [comment] 2023-04-06 20:26
Hi, video rendering depends on the system's video codecs. On Ubuntu, Pegasus uses the GStreamer video codecs (`gstreamer1.0-plugins-*` and `gstreamer1.0-libav`), while VLC uses its own set, as far as I know. If they don't work correctly, you can try installing more GStreamer packages (`libav` as mentioned earlier, or `gstreamer1.0-plugins-bad` and `gstreamer1.0-plugins-ugly`).

**Comment by tuxrinku** [comment] 2023-04-06 20:34
Hey, I tried that and they are already installed. Weirdly enough, it doesn't happen on my other machine on Ubuntu 22.10.

**Comment by mmatyas** [comment] 2023-08-25 10:32
There have been a Qt update recently, could you try the latest Pegasus?

**Comment by mmatyas** [comment] 2024-05-03 13:01
I'll close this for now, as the issue is related to third-party video codecs.

**Closed by mmatyas** 2024-05-03 13:01 UTC
