### ISSUE TITLE
Pegasus no longer detecting Playnite's library

### ISSUE THREAD

**Issue by HohiMonster** [mmatyas/pegasus-frontend#1061] opened 2023-06-24 11:41 UTC
I recently updated Playnite to it's latest version 10.18, after having used Playnite 8 for quite a while. But now Pegasus no longer detects my library on Playnite like it used to. I contacted Playnite support and they've told me that they have changed their library format since then, and that Pegasus needs an update to be able to detect it's new library format.

I really want to know if an update is being worked on regarding this, Pegasus has my favorite UI out of all the frontends I've tried and it detecting my whole library on Playnite saved me so much work. 

Kind regards.

**Comment by mmatyas** [comment] 2023-06-24 12:24
Hi! This issue sounds like the duplicate of #1032, so I'll close this one in favor of that. Unfortunately I haven't had enough time the past few months, but the issue was not forgotten, and I'd like to fix it eventually.

**Closed by mmatyas** 2023-06-24 12:24 UTC
